fix: reword leak warning to be more general

diff --git a/scripts/check-valgrind b/scripts/check-valgrind
--- a/scripts/check-valgrind
+++ b/scripts/check-valgrind
@@ -48,14 +48,14 @@ if [ -f valgrind-log.txt -a -s valgrind-log.txt ]
 then
     if [ -z "$NO_COLOR" ]
     then
-        printf '\033[7;33m LEAK \033[0m\n' 1>&2
+        printf '\033[7;33m WARN \033[0m\n' 1>&2
         printf '\033[1mReason:\033[0m\n' 1>&2
-        printf "memory test failed\n" 1>&2
+        printf "a memory error or leak was detected\n" 1>&2
         printf '\033[1mLog:\033[0m\n' 1>&2
     else
-        printf '[LEAK]\n' 1>&2
+        printf '[WARN]\n' 1>&2
         printf 'Reason:\n' 1>&2
-        printf "memory test failed\n" 1>&2
+        printf "a memory error or leak was detected\n" 1>&2
         printf 'Log:\n' 1>&2
     fi
 
